### ISSUE TITLE
Bitbucket link broken

### ISSUE THREAD

**Issue by dennishilmar** [joelgardner/git-line#5]
When trying to click the "View on Github" to open the bitbucket link its trying to open https://bitbucket.org/\<project\>/<repo>/commit/<CommitId> where the right URL is ".../commits/..." with an 's'.

**Comment by joelgardner** [comment]
Hey Dennis.  Definitely something that should work and is an easy fix, so I'll get on this today or tomorrow.  Of course, if you've got a PR that fixes, I'll merge it.

Thanks!

**Comment by joelgardner** [comment]
Fixed via https://github.com/joelgardner/git-line/pull/6 -- new minor version uploaded to the package repository.  Tested ssh/https cloned repos on both bitbucket and github.  Please open another issue if you see something weird.
